#!/usr/bin/env python3
"""
verify_env.py — AutoRobot Environment Verification

Checks that all dependencies and configuration are correctly set up
for running the AutoRobot autonomous reward-engineering pipeline.

Usage:
    python scripts/verify_env.py
"""

import importlib
import os
import sys


# ── Formatting helpers ──────────────────────────────────────────────────────

PASS = "PASS"
FAIL = "FAIL"
WARN = "WARN"

COL_WIDTHS = (50, 8)  # (check description, status)
SEPARATOR = "-" * (COL_WIDTHS[0] + COL_WIDTHS[1] + 3)


def row(description: str, status: str, detail: str = "") -> str:
    tag = f"[{status}]"
    line = f"  {description:<{COL_WIDTHS[0]}} {tag:<{COL_WIDTHS[1]}}"
    if detail:
        line += f"  {detail}"
    return line


# ── Individual checks ───────────────────────────────────────────────────────

def check_python_version() -> tuple:
    """Python version is 3.8.x."""
    v = sys.version_info
    version_str = f"{v.major}.{v.minor}.{v.micro}"
    if v.major == 3 and v.minor == 8:
        return PASS, version_str
    return FAIL, f"got {version_str}, need 3.8.x"


def check_import(module_name: str) -> tuple:
    """Generic importability check."""
    try:
        importlib.import_module(module_name)
        return PASS, ""
    except ImportError as exc:
        return FAIL, str(exc)


def check_torch_cuda() -> tuple:
    """torch is importable and CUDA is available."""
    try:
        import torch
    except ImportError:
        return FAIL, "torch not installed"
    if not torch.cuda.is_available():
        return FAIL, "torch imported but CUDA not available"
    return PASS, f"torch {torch.__version__}, CUDA {torch.version.cuda}"


def check_gpu_visible() -> tuple:
    """GPU is visible via torch.cuda."""
    try:
        import torch
    except ImportError:
        return FAIL, "torch not installed"
    count = torch.cuda.device_count()
    if count == 0:
        return FAIL, "no GPUs detected"
    names = [torch.cuda.get_device_name(i) for i in range(count)]
    return PASS, f"{count} GPU(s): {', '.join(names)}"


def check_env_var(var_name: str) -> tuple:
    """Environment variable exists and is non-empty."""
    val = os.environ.get(var_name, "")
    if val:
        # Mask the key for security — show first 4 and last 4 chars
        if len(val) > 12:
            masked = val[:4] + "..." + val[-4:]
        else:
            masked = "***"
        return PASS, f"set ({masked})"
    return FAIL, "not set"


def check_config_yaml() -> tuple:
    """config.yaml is present and parseable."""
    # Look for config.yaml relative to the project root
    candidates = [
        os.path.join(os.getcwd(), "config.yaml"),
        os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "config.yaml"),
    ]
    config_path = None
    for c in candidates:
        if os.path.isfile(c):
            config_path = c
            break
    if config_path is None:
        return FAIL, "config.yaml not found"
    try:
        import yaml
        with open(config_path, "r") as f:
            data = yaml.safe_load(f)
        if not isinstance(data, dict):
            return FAIL, "config.yaml did not parse as a dict"
        # Sanity: check a few expected keys
        missing = [k for k in ("llm", "training", "env") if k not in data]
        if missing:
            return WARN, f"parsed OK but missing keys: {missing}"
        return PASS, config_path
    except Exception as exc:
        return FAIL, str(exc)


def check_reward_py() -> tuple:
    """reward.py exists and defines compute_reward."""
    candidates = [
        os.path.join(os.getcwd(), "reward.py"),
        os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "reward.py"),
    ]
    reward_path = None
    for c in candidates:
        if os.path.isfile(c):
            reward_path = c
            break
    if reward_path is None:
        return WARN, "reward.py not found (will be generated by agent)"
    try:
        with open(reward_path, "r") as f:
            source = f.read()
        if "def compute_reward" in source:
            return PASS, "compute_reward function found"
        return FAIL, "reward.py exists but compute_reward not defined"
    except Exception as exc:
        return FAIL, str(exc)


# ── Main ────────────────────────────────────────────────────────────────────

def main():
    print()
    print("=" * (COL_WIDTHS[0] + COL_WIDTHS[1] + 3))
    print("  AutoRobot Environment Verification")
    print("=" * (COL_WIDTHS[0] + COL_WIDTHS[1] + 3))
    print()

    results = []

    # -- Python version --
    status, detail = check_python_version()
    results.append((f"Python version is 3.8.x", status, detail))

    # -- Core imports --
    status, detail = check_torch_cuda()
    results.append(("torch importable + CUDA available", status, detail))

    for mod_name, label in [
        ("isaacgym",     "isaacgym importable"),
        ("isaacgymenvs", "isaacgymenvs importable"),
        ("rl_games",     "rl_games importable"),
        ("openai",       "openai importable"),
    ]:
        status, detail = check_import(mod_name)
        results.append((label, status, detail))

    # -- GPU visibility --
    status, detail = check_gpu_visible()
    results.append(("GPU visible", status, detail))

    # -- Environment variables --
    status, detail = check_env_var("NEBIUS_API_KEY")
    results.append(("NEBIUS_API_KEY env var", status, detail))

    # -- Config --
    status, detail = check_config_yaml()
    results.append(("config.yaml parseable", status, detail))

    # -- reward.py --
    status, detail = check_reward_py()
    results.append(("reward.py has compute_reward", status, detail))

    # -- Print results table --
    print(SEPARATOR)
    print(f"  {'Check':<{COL_WIDTHS[0]}} {'Status':<{COL_WIDTHS[1]}}  Details")
    print(SEPARATOR)
    for desc, status, detail in results:
        print(row(desc, status, detail))
    print(SEPARATOR)
    print()

    # -- Summary --
    total = len(results)
    passed = sum(1 for _, s, _ in results if s == PASS)
    warned = sum(1 for _, s, _ in results if s == WARN)
    failed = sum(1 for _, s, _ in results if s == FAIL)

    print(f"  Total: {total}  |  Passed: {passed}  |  Warnings: {warned}  |  Failed: {failed}")
    print()

    if failed > 0:
        print("  Some checks FAILED. Review the output above and consult docs/SETUP.md.")
        print()
        sys.exit(1)
    elif warned > 0:
        print("  All critical checks passed. Warnings are non-blocking.")
        print()
        sys.exit(0)
    else:
        print("  All checks passed. Environment is ready!")
        print()
        sys.exit(0)


if __name__ == "__main__":
    main()
